last_n_days: 30
output_file: ./built/dev1.html
is_dev_mode: False
input_zip: ./example-data.d/csv.zip
habits_blacklist:
  - "ğŸ› Haare waschenğŸ”’"
  - "ğŸ—“ï¸ğŸ“¸ Kalender geteiltğŸ”’"
cell_values:
  - original: -1
    replacement: 'â”'
    legend: Forgot to track it.
  - original: 0
    replacement: "âŒ"
    legend: Expectation remained unfullfiled.
  - original: 1
    replacement: 'ğŸ†—'
    legend: Did a regular break.
  - original: 2
    replacement: 'âœ…'
    legend: Performed today ğŸ’ª